

import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


async function loadSheets(){
  const res = await fetch('https://dc66be1e-e9f3-4aae-822a-0b19de63250e.mock.pstmn.io/available_sheets',{
    credentials : 'include',
    
  });

  if(!res.ok){
    throw new Error("failed fetching data");
  }

  return await res.json();
}




export default async function RootLayout({ children }) {

  let sheetx =  await loadSheets();
  // console.log(sheetx);
 

  
  return (
    <html lang="en">
      <body className={`${inter.className} select-text min-h-screen bg-purple-100 flex flex-col `} >
      <NavBar  sheetx = {sheetx}/>
        {children}
      <Footer/>
        </body>
    </html>
  )
}
